apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- ../base

#namespace
namespace: kubesphere-sample-dev


# patch
patches:
- target:
    version: v1
    kind: Deployment
    group: apps
    name: ks-sample
  path: update_patch.yaml